dotfiles sync from kairo5-mbp

diff --git a/manager b/manager
--- a/manager
+++ b/manager
@@ -78,7 +78,7 @@ function subcmd_push() {
 	echo "commit msg: $commit_msg"
 	git -C "$repo_root" commit --all --message "$commit_msg" -q > /dev/null 2>&1
 	git -C "$repo_root" push -uq origin master > /dev/null 2>&1
-	if [$? -ne 0 ]; then echo "Error: Failed to push dotfiles repo" && return 1; fi
+	if [ $? -ne 0 ]; then echo "Error: Failed to push dotfiles repo" && return 1; fi
 	remote_url=$(git -C "$repo_root" remote -v | grep push | grep -Eo "[[:space:]].*[[:space:]]" | tr -d '[:space:]')
 	echo "Successfull push from $remote_url"
 }
